entities added
ALLHUBS-Jan-2024-Liftoff/Black-Jackets pull request #11
Opened 2024-07-13 18:37 UTC by fowlerrc

2024-07-13 18:52 UTC, mmcadoulos commented
These entities need to be inside a `models` package. Create the `models` package inside the package they are currently in and move them there. You will need to refactor line 1 in each of them to reflect what package they are in. Compare with previous assignments on how it should look.

2024-07-16 23:13 UTC, mmcadoulos commented on BlackJackets API/src/main/java/BlackJackets/BlackJackets/Models/Band.java
After our talk about data structure, we decided that band entities would not be needed for the MVP. Let's go ahead and delete this until we reach phase 2.

2024-07-16 23:16 UTC, mmcadoulos commented on BlackJackets API/src/main/resources/application.properties
This file shouldn't have been changed from what is in main. Could you change it back and make sure you update your MySQL Workbench accordingly? You can just copy and paste it from GitHub :)

2024-07-16 23:18 UTC, mmcadoulos commented on BlackJackets-ui/.gitignore
Somehow the "?" on line 24 got removed. I'm not sure why or what it is there for but it might be best to add it back in case it was important.

2024-07-16 23:19 UTC, mmcadoulos requested changes
I added some comments to a couple files. If you can't see them let me know and we can work through it.

2024-07-17 00:57 UTC, mmcadoulos submitted a review, later dismissed

2024-07-18 02:56 UTC, ayjsh approved these changes
I think it looks good to me.

2024-07-18 03:31 UTC, arevathi125 approved these changes
It looks good. Please remove commented lines.

2024-07-18 03:33 UTC, merged